// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZeqMrqDjHXbEj5vScswq-MFfmsCNBSXQ',
    appId: '1:691444699986:web:46637a1830771f8b7c208b',
    messagingSenderId: '691444699986',
    projectId: 'union-shop-80822',
    authDomain: 'union-shop-80822.firebaseapp.com',
    storageBucket: 'union-shop-80822.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE3hY2Pg8CkXYCe78rGQYBDS8edY-600Y',
    appId: '1:691444699986:android:0881a45d35a304d77c208b',
    messagingSenderId: '691444699986',
    projectId: 'union-shop-80822',
    storageBucket: 'union-shop-80822.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUVmJr7JQvV2ttFIizC8V75vWFG4GHVrk',
    appId: '1:691444699986:ios:748e99125d7dae657c208b',
    messagingSenderId: '691444699986',
    projectId: 'union-shop-80822',
    storageBucket: 'union-shop-80822.firebasestorage.app',
    iosBundleId: 'com.example.unionShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUVmJr7JQvV2ttFIizC8V75vWFG4GHVrk',
    appId: '1:691444699986:ios:748e99125d7dae657c208b',
    messagingSenderId: '691444699986',
    projectId: 'union-shop-80822',
    storageBucket: 'union-shop-80822.firebasestorage.app',
    iosBundleId: 'com.example.unionShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZeqMrqDjHXbEj5vScswq-MFfmsCNBSXQ',
    appId: '1:691444699986:web:ebbe5d46d919af677c208b',
    messagingSenderId: '691444699986',
    projectId: 'union-shop-80822',
    authDomain: 'union-shop-80822.firebaseapp.com',
    storageBucket: 'union-shop-80822.firebasestorage.app',
  );
}
